## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry

## Cloudcasa AMDS Cluster ID. To be provided by the user.
cluster_id: ""
